repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.11.0'
  hooks:
    - id: ruff
      args: [--fix]
      name: ruff (check and fix)
      always_run: true
    - id: ruff
      args: [--select=I, --fix]
      name: ruff (import sorting)
      always_run: true
    - id: ruff-format
      name: ruff (format)
      always_run: true

- repo: local
  hooks:
    - id: commit-msg-template
      name: Check commit message format
      entry: python .pre-commit_msg_template.py
      language: python
      stages: [commit-msg]
      always_run: true