"""Example custom crypto plugin for Swarm Squad Ep1."""

from __future__ import annotations

import hashlib
import hmac


def _xor_mask(key: bytes, seed: bytes, length: int) -> bytes:
    block = hmac.new(key, seed, hashlib.sha256).digest()
    repeats = (length // len(block)) + 1
    return (block * repeats)[:length]


def xor_hmac_sign(*, key: bytes, data: bytes, sender_id: str, crypto=None) -> bytes:
    """
    Demo custom signer: XOR obfuscation + HMAC integrity.

    Returns encrypted_payload + mac, where mac is HMAC-SHA256(sender_id||encrypted_payload).
    """
    sender = sender_id.encode("utf-8")
    mask = _xor_mask(key, sender + data, len(data))
    encrypted = bytes(d ^ m for d, m in zip(data, mask))
    mac = hmac.new(key, sender + encrypted, hashlib.sha256).digest()
    return encrypted + mac


def xor_hmac_verify(
    *,
    key: bytes,
    data: bytes,
    signature: bytes,
    sender_id: str,
    crypto=None,
) -> bool:
    """Verify signature generated by `xor_hmac_sign`."""
    if len(signature) < 32:
        return False
    sender = sender_id.encode("utf-8")
    encrypted = signature[:-32]
    received_mac = signature[-32:]
    expected_mac = hmac.new(key, sender + encrypted, hashlib.sha256).digest()
    if not hmac.compare_digest(received_mac, expected_mac):
        return False

    mask = _xor_mask(key, sender + data, len(data))
    expected_encrypted = bytes(d ^ m for d, m in zip(data, mask))
    return hmac.compare_digest(encrypted, expected_encrypted)
